# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class GenomeComparisonSDK(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def build_pangenome(self, input, context=None):
        """
        :param input: instance of type "BuildPangenomeParams" -> structure:
           parameter "genome_refs" of list of String, parameter
           "genomeset_ref" of String, parameter "workspace" of String,
           parameter "output_id" of String
        :returns: instance of type "BuildPangenomeResult" -> structure:
           parameter "report_name" of String, parameter "report_ref" of
           String, parameter "pg_ref" of String
        """
        return self._client.call_method(
            'GenomeComparisonSDK.build_pangenome',
            [input], self._service_ver, context)

    def compare_genomes(self, params, context=None):
        """
        Compares the specified genomes and computes unique features and core features
        :param params: instance of type "CompareGenomesParams" -> structure:
           parameter "pangenome_ref" of String, parameter "protcomp_ref" of
           String, parameter "output_id" of String, parameter "workspace" of
           String
        :returns: instance of type "CompareGenomesResult" -> structure:
           parameter "report_name" of String, parameter "report_ref" of
           String, parameter "cg_ref" of String
        """
        return self._client.call_method(
            'GenomeComparisonSDK.compare_genomes',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('GenomeComparisonSDK.status',
                                        [], self._service_ver, context)
